add seminar und beratung
kreinn/ub-burzlaff pull request #15
Opened 2018-03-05 15:10 UTC by jo2

fix #14

2018-03-05 15:23 UTC, silasmahler requested changes
Die Links sind auf der Hauptseite noch nicht ersichtlich, vllt ein Button mit "Mehr" oder "Details", die Übersichtseiten könnten noch etwas mehr css styling vertragen (mit dem Theme-CSS), sonst gut

2018-03-12 08:26 UTC, wirebug commented
Die Navigationsleiste sollte zu jeder Zeit unverändert bleiben. Lieber eine Subnavi unter "Leistungen" für Seminarangebot, Beratung & Workshops einfügen.
Auf den Subseiten würde ich dann keine 100%tige Höhe für das Header-Bild wählen. Besserwäre hier vll 50% oder die Section "Leistungen" aus der Hauptseite oben.

2018-03-25 19:13 UTC, jo2 commented
bitte erneut prüfen

2018-03-26 11:06 UTC, silasmahler commented
Der Button "mehr" sieht nun gut aus, ich würde nun die unterseiten-menüs farblich ebenfalls anpassen und die Navigationsleiste 
![grafik](https://user-images.githubusercontent.com/14834495/37902947-6e0011d8-30f6-11e8-8701-a17b13475228.png)
"Home/seminarangebot" dort noch entfernen und eher einen zurück-button einfügen, die fügt sich nicht gut ein @wirebug

2018-03-26 11:06 UTC, wirebug reviewed
custom css should be hold in a sass file in a later ticket

2018-03-26 11:11 UTC, silasmahler commented
Zusätzlich wurde ich den Teil der Unterseite 
![grafik](https://user-images.githubusercontent.com/14834495/37903074-edb523aa-30f6-11e8-8335-cba88371b49d.png)
entfernen und lieber in der Navigationsleiste einen Dropdown anbieten, der dann ausgeklappt ist, das wirkt sonst etwas merkwürdig von der Struktur.
Alternativ keine Unterseiten und ein Modalfenster mit den Seminarangeboten, ist ja eigentlich als SinglePage gedacht

2018-03-26 13:59 UTC, wirebug commented
Ich würde das Ticket erstmal so freigeben. Alles andere in weiteren Tickets

2018-03-26 13:59 UTC, wirebug approved these changes

2018-03-29 09:53 UTC, silasmahler commented
@jo2 @wirebug Ich habe heute von Norbert Feedback bekommen und mit ihm mögliche Optionen diskutiert. Die Seminar- und Workshopbeschreibungen sollen als Modalfenster auf der Hauptseite eingebunden werden.

2018-03-29 10:01 UTC, silasmahler commented
Zusätzlich sollen in der Desktopversion die "Mehr erfahren" Buttons horizontal auf einer Linie liegen.

2018-03-29 10:50 UTC, jo2 commented
ich glaube das issue 31 an dieser stelle nicht der richtige ist

2018-03-29 12:51 UTC, jo2 commented
so pullrequest geupdated

2018-04-01 11:36 UTC, silasmahler commented
Die Popups müssen noch Mobil-Optimiert werden

2018-04-01 14:58 UTC, jo2 commented
geupdated

2018-04-01 18:32 UTC, silasmahler commented
- [ ] Mobil müssten die Columns anders aufgeteilt werden.
siehe:
![grafik](https://user-images.githubusercontent.com/14834495/38176211-6574fde0-35eb-11e8-82e8-dfef6c0a0a83.png)

Die Desktop-Version nutzt nun weniger Platz, aber ich finde dass es gut aussieht. @wirebug Was sagst du dazu?
![grafik](https://user-images.githubusercontent.com/14834495/38176229-9ce703ae-35eb-11e8-866c-5cf25aa2b653.png)

2018-04-01 22:40 UTC, jo2 commented
jetzt sollte es passen

2018-04-01 23:11 UTC, silasmahler commented
- Sieht soweit gut aus, gute Arbeit @jo2 :+1:

2018-04-01 23:35 UTC, silasmahler approved these changes

2018-04-01 23:37 UTC, merged